version: '3.8'

services:
  # Development overrides
  app:
    build:
      target: builder
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - app_logs:/app/logs
    command: npm run dev
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    stdin_open: true
    tty: true

  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tercih_sihirbazi_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d

  # Development Redis with exposed port
  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local